FROM dockerfile/java:openjdk-7-jdk
MAINTAINER tksukhu@gmail.com
EXPOSE 8080
CMD java -jar spring-boot-restful-service.jar
ADD build/spring-boot-restful-service.jar /data/spring-boot-restful-service.jar

